Started by user [8mha:////4Maezfk0JbHDzak4BfSdZmgwP4IA8xVqOrqfKRXTMeqbAAAAlx+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzWEgZu/dLi1CL9xJTczDwAj6GcLcAAAAA=[0madmin
[8mha:////4KRo0YmmwtC2y6yPDiNjzM5sfeXF5Vp/3whR1HckqUrwAAAAoh+LCAAAAAAAAP9tjTEOwjAQBM8BClpKHuFItIiK1krDC0x8GCfWnbEdkooX8TX+gCESFVvtrLSa5wtWKcKBo5UdUu8otU4GP9jS5Mixv3geZcdn2TIl9igbHBs2eJyx4YwwR1SwULBGaj0nRzbDRnX6rmuvydanHMu2V1A5c4MHCFXMWcf8hSnC9jqYxPTz/BXAFEIGsfuclm8zQVqFvQAAAA==[0m[Pipeline] Start of Pipeline
[8mha:////4Hpqw+HJtSJOYxqblEvzq25+39uAue/8cP6aI45kCxT9AAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycohUghExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jduZBmjwAAAAA==[0m[Pipeline] node
Running on [8mha:////4IoS6Q6HEmADU0+DF7n0QTp/dLGB5vjQX3rtbzxAHVkqAAAAqB+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAz2EgYZ/dzEvMT0VP3k/NyC0pLUIn2NpNLMnBLdzDxNfQB9z6/O0QAAAA==[0mJenkins in /var/jenkins_home/workspace/automation-tests
[8mha:////4N7pT5rmqmbLvcSM/83ZQbUOFRSgurB9IZiC2xYdP+2yAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gA0xsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfoP95RwAAAAA==[0m[Pipeline] {
[8mha:////4HieURhCKaY8XeTlYcVKy4MN28X/fW/Ye6Dg9+NNb90uAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gQkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jc09154wAAAAA==[0m[Pipeline] stage
[8mha:////4G7vxwlo8zq62UeiqVhB7jY1RFzjOZMgZSrhtusUQqxXAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0ggUxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jek7ggRwAAAAA==[0m[Pipeline] { (checkout)
[8mha:////4LFsx75kGytnbGiDi+2IyQdeVDV2QftKxw5qohZPvFJrAAAAoh+LCAAAAAAAAP9tjTEOAiEURD9rLGwtPQTbaWGsbAmNJ0AWEZb8zwLrbuWJvJp3kLiJlZNMMm+a93rDOic4UbLcG+wdZu14DKOti0+U+lugiXu6ck2YKRguzSSpM+cFJRUDS1gDKwEbgzpQdmgLbIVXD9UGhba9lFS/o4DGdQM8gYlqLiqVL8wJdvexy4Q/z18BzLEA29ce4gfg7KmOvAAAAA==[0m[Pipeline] git
The recommended git tool is: NONE
No credentials specified
 > git rev-parse --resolve-git-dir /var/jenkins_home/workspace/automation-tests/.git # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/Fatalwgx/pytest-lesson1 # timeout=10
Fetching upstream changes from https://github.com/Fatalwgx/pytest-lesson1
 > git --version # timeout=10
 > git --version # 'git version 2.30.2'
 > git fetch --tags --force --progress -- https://github.com/Fatalwgx/pytest-lesson1 +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/main^{commit} # timeout=10
Checking out Revision aed10f5ef5a1146245b7216aa37dd24aa32ce297 (refs/remotes/origin/main)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f aed10f5ef5a1146245b7216aa37dd24aa32ce297 # timeout=10
 > git branch -a -v --no-abbrev # timeout=10
 > git checkout -b main aed10f5ef5a1146245b7216aa37dd24aa32ce297 # timeout=10
Commit message: "fix"
First time build. Skipping changelog.
[8mha:////4OTvoH0qmSkW0AUK+EqLJib4CDbM0uMYmDNBmnGEyOgqAAAAoh+LCAAAAAAAAP9tjTEOAiEURD9rLGwtPQTbGRNjZUtoPAGyiLDkfxZYdytP5NW8g8RNrJxkknnTvNcb1jnBiZLl3mDvMGvHYxhtXXyi1N8CTdzTlWvCTMFwaSZJnTkvKKkYWMIaWAnYGNSBskNbYCu8eqg2KLTtpaT6HQU0rhvgCUxUc1GpfGFOsLuPXSb8ef4KYI6xADvU7j9Dg2gqvAAAAA==[0m[Pipeline] }
[8mha:////4M+bWZwGAe5LdF6zWKAg50C+4LHxMjq7KswGa3lAQsnrAAAAoh+LCAAAAAAAAP9tjTEOAiEURD9rLGwtPQRbWRhjZUtoPAGyiLDkfxZYdytP5NW8g8RNrJxkknnTvNcb1jnBiZLl3mDvMGvHYxhtXXyi1N8CTdzTlWvCTMFwaSZJnTkvKKkYWMIaWAnYGNSBskNbYCu8eqg2KLTtpaT6HQU0rhvgCUxUc1GpfGFOsLuPXSb8ef4KYI6xADvU7j9J+wGOvAAAAA==[0m[Pipeline] // stage
[8mha:////4Gz4pYzjVO1aPtie40eio3FcL+piICEb2nKXwcZEPyjXAAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQDEh2iorXc8AITG+PEugv2haTiRXyNPxCIRMVWOyut5vmCMic4UPKycdgGzHWQXez91ORAqb1EGmRDZ1kTZopOajdosu44oyZ2MEcUsFCwdFhHygE9w0o15m6qaNBXJ07TtldQBHuDBwg1mdkk/sKYYH3tbSb8ef4KYOwYxI6h2G4+x/INtuQqUcEAAAA=[0m[Pipeline] stage
[8mha:////4ObIJr3HdheyVxK+2JTu/ob8/daHGKVQEe3DD/LeCEC7AAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+DOrAycoiUzoiJNerCCUITQtLo/zZJSSdOxNW4Ay2VmPBg2Zas93pDGQOcKBjuNHYWY2t570czJ54pdDdPmTu68pYwkte80bkhpc9rbShpWFUw2AjYamw9RYsmwU44+ZCVl2iqSwrzdhTArBrgCYWYyUmG9C1TgP19VJHwx/kLgKlPwOrDYvXyLD8BobDcwgAAAA==[0m[Pipeline] { (Hello)
[8mha:////4P9u4wcbskH7kBEZ2yAJn5BXkcbvmZx96ecduGCF3V6lAAAAox+LCAAAAAAAAP9tjTESwiAURH/iWNhaeggysXWsbBkaT4AJIoT5nwCRVJ7Iq3kH0cxYucXOvm3e8wXrGOBIQTOrcDAYO8O8m3RZLFMYro4ys3RhHWEkp5hQWVCvTgsKSgqWVDWsOGwUdo6iQZ1gy628y8ZJ1M05hfIdONSmH+EBFS/mJEP6whxgd5v6SPjz/BXA7BPUbfupvX8DpQJrNb4AAAA=[0m[Pipeline] sh
+ pytest
============================= test session starts ==============================
platform linux -- Python 3.9.2, pytest-7.3.1, pluggy-1.0.0
rootdir: /var/jenkins_home/workspace/automation-tests
configfile: pyproject.toml
plugins: allure-pytest-2.13.2
collected 6 items

tests/test_fixtures.py FEFE                                              [ 33%]
tests/test_indirect.py FEsE                                              [ 66%]
tests/test_parametrized.py FEFE                                          [100%]

==================================== ERRORS ====================================
______________________ ERROR at teardown of test_desktop _______________________

    @pytest.fixture(scope='function', autouse=True)
    def browser_management():
        browser.config.base_url = os.getenv('selene.base_url', 'https://github.com')
        browser.config.browser_name = os.getenv('selene.browser_name', 'chrome')
        browser.config.hold_browser_open = (os.getenv('selene.hold_browser_open', 'false').lower() == 'true')
        browser.config.timeout = float(os.getenv('selene.timeout', '3'))
        yield
>       browser.quit()

tests/conftest.py:32: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.9/dist-packages/selene/core/entity.py:1204: in quit
    self.driver.quit()
/usr/local/lib/python3.9/dist-packages/selene/core/entity.py:1099: in driver
    return self.config.driver
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:345: in __get__
    driver = config.build_driver_strategy(config)
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:173: in _build_local_driver_by_name_or_remote_by_url_and_options
    return {  # type: ignore
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:93: in install_and_build_chrome
    return Chrome(
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chrome/webdriver.py:84: in __init__
    super().__init__(
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chromium/webdriver.py:101: in __init__
    self.service.start()
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py:100: in start
    self.assert_process_still_running()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selenium.webdriver.chrome.service.Service object at 0x7f0f3cac9a60>

    def assert_process_still_running(self) -> None:
        """Check if the underlying process is still running."""
        return_code = self.process.poll()
        if return_code:
>           raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
E           selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/113.0.5672.63/chromedriver unexpectedly exited. Status code was: 127

/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py:113: WebDriverException
----------------------------- Captured stderr call -----------------------------
[WDM] - Downloading:   0%|          | 0.00/6.98M [00:00<?, ?B/s][WDM] - Downloading:   1%|▏         | 104k/6.98M [00:00<00:07, 1.02MB/s][WDM] - Downloading:   8%|▊         | 536k/6.98M [00:00<00:02, 2.98MB/s][WDM] - Downloading:  21%|██        | 1.46M/6.98M [00:00<00:00, 6.07MB/s][WDM] - Downloading:  35%|███▌      | 2.45M/6.98M [00:00<00:00, 7.71MB/s][WDM] - Downloading:  49%|████▉     | 3.41M/6.98M [00:00<00:00, 8.56MB/s][WDM] - Downloading:  62%|██████▏   | 4.32M/6.98M [00:00<00:00, 8.84MB/s][WDM] - Downloading:  77%|███████▋  | 5.37M/6.98M [00:00<00:00, 9.51MB/s][WDM] - Downloading:  92%|█████████▏| 6.40M/6.98M [00:00<00:00, 9.85MB/s][WDM] - Downloading: 100%|██████████| 6.98M/6.98M [00:00<00:00, 8.44MB/s]
_______________________ ERROR at teardown of test_mobile _______________________

    @pytest.fixture(scope='function', autouse=True)
    def browser_management():
        browser.config.base_url = os.getenv('selene.base_url', 'https://github.com')
        browser.config.browser_name = os.getenv('selene.browser_name', 'chrome')
        browser.config.hold_browser_open = (os.getenv('selene.hold_browser_open', 'false').lower() == 'true')
        browser.config.timeout = float(os.getenv('selene.timeout', '3'))
        yield
>       browser.quit()

tests/conftest.py:32: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.9/dist-packages/selene/core/entity.py:1204: in quit
    self.driver.quit()
/usr/local/lib/python3.9/dist-packages/selene/core/entity.py:1099: in driver
    return self.config.driver
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:345: in __get__
    driver = config.build_driver_strategy(config)
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:173: in _build_local_driver_by_name_or_remote_by_url_and_options
    return {  # type: ignore
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:93: in install_and_build_chrome
    return Chrome(
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chrome/webdriver.py:84: in __init__
    super().__init__(
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chromium/webdriver.py:101: in __init__
    self.service.start()
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py:100: in start
    self.assert_process_still_running()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selenium.webdriver.chrome.service.Service object at 0x7f0f3ca88c40>

    def assert_process_still_running(self) -> None:
        """Check if the underlying process is still running."""
        return_code = self.process.poll()
        if return_code:
>           raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
E           selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/113.0.5672.63/chromedriver unexpectedly exited. Status code was: 127

/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py:113: WebDriverException
________ ERROR at teardown of test_parametrized_indirect[application0] _________

    @pytest.fixture(scope='function', autouse=True)
    def browser_management():
        browser.config.base_url = os.getenv('selene.base_url', 'https://github.com')
        browser.config.browser_name = os.getenv('selene.browser_name', 'chrome')
        browser.config.hold_browser_open = (os.getenv('selene.hold_browser_open', 'false').lower() == 'true')
        browser.config.timeout = float(os.getenv('selene.timeout', '3'))
        yield
>       browser.quit()

tests/conftest.py:32: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.9/dist-packages/selene/core/entity.py:1204: in quit
    self.driver.quit()
/usr/local/lib/python3.9/dist-packages/selene/core/entity.py:1099: in driver
    return self.config.driver
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:345: in __get__
    driver = config.build_driver_strategy(config)
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:173: in _build_local_driver_by_name_or_remote_by_url_and_options
    return {  # type: ignore
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:93: in install_and_build_chrome
    return Chrome(
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chrome/webdriver.py:84: in __init__
    super().__init__(
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chromium/webdriver.py:101: in __init__
    self.service.start()
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py:100: in start
    self.assert_process_still_running()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selenium.webdriver.chrome.service.Service object at 0x7f0f3cab9b50>

    def assert_process_still_running(self) -> None:
        """Check if the underlying process is still running."""
        return_code = self.process.poll()
        if return_code:
>           raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
E           selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/113.0.5672.63/chromedriver unexpectedly exited. Status code was: 127

/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py:113: WebDriverException
________ ERROR at teardown of test_parametrized_indirect[application1] _________

    @pytest.fixture(scope='function', autouse=True)
    def browser_management():
        browser.config.base_url = os.getenv('selene.base_url', 'https://github.com')
        browser.config.browser_name = os.getenv('selene.browser_name', 'chrome')
        browser.config.hold_browser_open = (os.getenv('selene.hold_browser_open', 'false').lower() == 'true')
        browser.config.timeout = float(os.getenv('selene.timeout', '3'))
        yield
>       browser.quit()

tests/conftest.py:32: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.9/dist-packages/selene/core/entity.py:1204: in quit
    self.driver.quit()
/usr/local/lib/python3.9/dist-packages/selene/core/entity.py:1099: in driver
    return self.config.driver
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:345: in __get__
    driver = config.build_driver_strategy(config)
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:173: in _build_local_driver_by_name_or_remote_by_url_and_options
    return {  # type: ignore
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:93: in install_and_build_chrome
    return Chrome(
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chrome/webdriver.py:84: in __init__
    super().__init__(
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chromium/webdriver.py:101: in __init__
    self.service.start()
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py:100: in start
    self.assert_process_still_running()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selenium.webdriver.chrome.service.Service object at 0x7f0f3ca7e490>

    def assert_process_still_running(self) -> None:
        """Check if the underlying process is still running."""
        return_code = self.process.poll()
        if return_code:
>           raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
E           selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/113.0.5672.63/chromedriver unexpectedly exited. Status code was: 127

/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py:113: WebDriverException
_______________ ERROR at teardown of test_parametrized[Desktop] ________________

    @pytest.fixture(scope='function', autouse=True)
    def browser_management():
        browser.config.base_url = os.getenv('selene.base_url', 'https://github.com')
        browser.config.browser_name = os.getenv('selene.browser_name', 'chrome')
        browser.config.hold_browser_open = (os.getenv('selene.hold_browser_open', 'false').lower() == 'true')
        browser.config.timeout = float(os.getenv('selene.timeout', '3'))
        yield
>       browser.quit()

tests/conftest.py:32: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.9/dist-packages/selene/core/entity.py:1204: in quit
    self.driver.quit()
/usr/local/lib/python3.9/dist-packages/selene/core/entity.py:1099: in driver
    return self.config.driver
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:345: in __get__
    driver = config.build_driver_strategy(config)
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:173: in _build_local_driver_by_name_or_remote_by_url_and_options
    return {  # type: ignore
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:93: in install_and_build_chrome
    return Chrome(
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chrome/webdriver.py:84: in __init__
    super().__init__(
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chromium/webdriver.py:101: in __init__
    self.service.start()
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py:100: in start
    self.assert_process_still_running()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selenium.webdriver.chrome.service.Service object at 0x7f0f3ca43c70>

    def assert_process_still_running(self) -> None:
        """Check if the underlying process is still running."""
        return_code = self.process.poll()
        if return_code:
>           raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
E           selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/113.0.5672.63/chromedriver unexpectedly exited. Status code was: 127

/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py:113: WebDriverException
________________ ERROR at teardown of test_parametrized[Mobile] ________________

    @pytest.fixture(scope='function', autouse=True)
    def browser_management():
        browser.config.base_url = os.getenv('selene.base_url', 'https://github.com')
        browser.config.browser_name = os.getenv('selene.browser_name', 'chrome')
        browser.config.hold_browser_open = (os.getenv('selene.hold_browser_open', 'false').lower() == 'true')
        browser.config.timeout = float(os.getenv('selene.timeout', '3'))
        yield
>       browser.quit()

tests/conftest.py:32: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.9/dist-packages/selene/core/entity.py:1204: in quit
    self.driver.quit()
/usr/local/lib/python3.9/dist-packages/selene/core/entity.py:1099: in driver
    return self.config.driver
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:345: in __get__
    driver = config.build_driver_strategy(config)
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:173: in _build_local_driver_by_name_or_remote_by_url_and_options
    return {  # type: ignore
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:93: in install_and_build_chrome
    return Chrome(
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chrome/webdriver.py:84: in __init__
    super().__init__(
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chromium/webdriver.py:101: in __init__
    self.service.start()
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py:100: in start
    self.assert_process_still_running()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selenium.webdriver.chrome.service.Service object at 0x7f0f3cbbebe0>

    def assert_process_still_running(self) -> None:
        """Check if the underlying process is still running."""
        return_code = self.process.poll()
        if return_code:
>           raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
E           selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/113.0.5672.63/chromedriver unexpectedly exited. Status code was: 127

/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py:113: WebDriverException
=================================== FAILURES ===================================
_________________________________ test_desktop _________________________________

desktop_resolution = None

    def test_desktop(desktop_resolution):
>       browser.open('/')

tests/test_fixtures.py:6: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.9/dist-packages/selene/core/entity.py:1154: in open
    self.config._executor.get_url(relative_or_absolute_url)
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:303: in get_url
    self.config._driver_get_url_strategy(self.config)(url)
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:218: in get
    driver = config.driver
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:345: in __get__
    driver = config.build_driver_strategy(config)
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:173: in _build_local_driver_by_name_or_remote_by_url_and_options
    return {  # type: ignore
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:93: in install_and_build_chrome
    return Chrome(
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chrome/webdriver.py:84: in __init__
    super().__init__(
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chromium/webdriver.py:101: in __init__
    self.service.start()
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py:100: in start
    self.assert_process_still_running()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selenium.webdriver.chrome.service.Service object at 0x7f0f3d808bb0>

    def assert_process_still_running(self) -> None:
        """Check if the underlying process is still running."""
        return_code = self.process.poll()
        if return_code:
>           raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
E           selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/113.0.5672.63/chromedriver unexpectedly exited. Status code was: 127

/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py:113: WebDriverException
----------------------------- Captured stderr call -----------------------------
[WDM] - Downloading:   0%|          | 0.00/6.98M [00:00<?, ?B/s][WDM] - Downloading:   1%|▏         | 104k/6.98M [00:00<00:07, 1.02MB/s][WDM] - Downloading:   8%|▊         | 536k/6.98M [00:00<00:02, 2.98MB/s][WDM] - Downloading:  21%|██        | 1.46M/6.98M [00:00<00:00, 6.07MB/s][WDM] - Downloading:  35%|███▌      | 2.45M/6.98M [00:00<00:00, 7.71MB/s][WDM] - Downloading:  49%|████▉     | 3.41M/6.98M [00:00<00:00, 8.56MB/s][WDM] - Downloading:  62%|██████▏   | 4.32M/6.98M [00:00<00:00, 8.84MB/s][WDM] - Downloading:  77%|███████▋  | 5.37M/6.98M [00:00<00:00, 9.51MB/s][WDM] - Downloading:  92%|█████████▏| 6.40M/6.98M [00:00<00:00, 9.85MB/s][WDM] - Downloading: 100%|██████████| 6.98M/6.98M [00:00<00:00, 8.44MB/s]
_________________________________ test_mobile __________________________________

mobile_resolution = None

    def test_mobile(mobile_resolution):
>       browser.open('/')

tests/test_fixtures.py:11: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.9/dist-packages/selene/core/entity.py:1154: in open
    self.config._executor.get_url(relative_or_absolute_url)
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:303: in get_url
    self.config._driver_get_url_strategy(self.config)(url)
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:218: in get
    driver = config.driver
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:345: in __get__
    driver = config.build_driver_strategy(config)
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:173: in _build_local_driver_by_name_or_remote_by_url_and_options
    return {  # type: ignore
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:93: in install_and_build_chrome
    return Chrome(
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chrome/webdriver.py:84: in __init__
    super().__init__(
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chromium/webdriver.py:101: in __init__
    self.service.start()
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py:100: in start
    self.assert_process_still_running()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selenium.webdriver.chrome.service.Service object at 0x7f0f3cac22b0>

    def assert_process_still_running(self) -> None:
        """Check if the underlying process is still running."""
        return_code = self.process.poll()
        if return_code:
>           raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
E           selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/113.0.5672.63/chromedriver unexpectedly exited. Status code was: 127

/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py:113: WebDriverException
___________________ test_parametrized_indirect[application0] ___________________

application = None

    @pytest.mark.parametrize("application", [(900, 600), (1980, 1024)], indirect=True)
    def test_parametrized_indirect(application):
        if (browser.config.window_width != 900) and (browser.config.window_height != 600):
            pytest.skip("Full HD is unsuitable for mobile tests")
>       browser.open('/')

tests/test_indirect.py:10: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.9/dist-packages/selene/core/entity.py:1154: in open
    self.config._executor.get_url(relative_or_absolute_url)
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:303: in get_url
    self.config._driver_get_url_strategy(self.config)(url)
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:218: in get
    driver = config.driver
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:345: in __get__
    driver = config.build_driver_strategy(config)
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:173: in _build_local_driver_by_name_or_remote_by_url_and_options
    return {  # type: ignore
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:93: in install_and_build_chrome
    return Chrome(
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chrome/webdriver.py:84: in __init__
    super().__init__(
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chromium/webdriver.py:101: in __init__
    self.service.start()
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py:100: in start
    self.assert_process_still_running()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selenium.webdriver.chrome.service.Service object at 0x7f0f3cb92850>

    def assert_process_still_running(self) -> None:
        """Check if the underlying process is still running."""
        return_code = self.process.poll()
        if return_code:
>           raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
E           selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/113.0.5672.63/chromedriver unexpectedly exited. Status code was: 127

/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py:113: WebDriverException
__________________________ test_parametrized[Desktop] __________________________

width = 1980, height = 1024

    @pytest.mark.parametrize(["width", "height"], [(1980, 1024), (900, 600)], ids=["Desktop", "Mobile"])
    def test_parametrized(width, height):
        browser.config.window_width = width
        browser.config.window_height = height
>       browser.open('/')

tests/test_parametrized.py:10: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.9/dist-packages/selene/core/entity.py:1154: in open
    self.config._executor.get_url(relative_or_absolute_url)
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:303: in get_url
    self.config._driver_get_url_strategy(self.config)(url)
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:218: in get
    driver = config.driver
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:345: in __get__
    driver = config.build_driver_strategy(config)
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:173: in _build_local_driver_by_name_or_remote_by_url_and_options
    return {  # type: ignore
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:93: in install_and_build_chrome
    return Chrome(
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chrome/webdriver.py:84: in __init__
    super().__init__(
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chromium/webdriver.py:101: in __init__
    self.service.start()
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py:100: in start
    self.assert_process_still_running()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selenium.webdriver.chrome.service.Service object at 0x7f0f3cb27d30>

    def assert_process_still_running(self) -> None:
        """Check if the underlying process is still running."""
        return_code = self.process.poll()
        if return_code:
>           raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
E           selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/113.0.5672.63/chromedriver unexpectedly exited. Status code was: 127

/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py:113: WebDriverException
__________________________ test_parametrized[Mobile] ___________________________

width = 900, height = 600

    @pytest.mark.parametrize(["width", "height"], [(1980, 1024), (900, 600)], ids=["Desktop", "Mobile"])
    def test_parametrized(width, height):
        browser.config.window_width = width
        browser.config.window_height = height
>       browser.open('/')

tests/test_parametrized.py:10: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.9/dist-packages/selene/core/entity.py:1154: in open
    self.config._executor.get_url(relative_or_absolute_url)
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:303: in get_url
    self.config._driver_get_url_strategy(self.config)(url)
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:218: in get
    driver = config.driver
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:345: in __get__
    driver = config.build_driver_strategy(config)
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:173: in _build_local_driver_by_name_or_remote_by_url_and_options
    return {  # type: ignore
/usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:93: in install_and_build_chrome
    return Chrome(
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chrome/webdriver.py:84: in __init__
    super().__init__(
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chromium/webdriver.py:101: in __init__
    self.service.start()
/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py:100: in start
    self.assert_process_still_running()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <selenium.webdriver.chrome.service.Service object at 0x7f0f3cb64730>

    def assert_process_still_running(self) -> None:
        """Check if the underlying process is still running."""
        return_code = self.process.poll()
        if return_code:
>           raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
E           selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/113.0.5672.63/chromedriver unexpectedly exited. Status code was: 127

/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/service.py:113: WebDriverException
=============================== warnings summary ===============================
tests/test_fixtures.py::test_desktop
tests/test_fixtures.py::test_mobile
tests/test_indirect.py::test_parametrized_indirect[application0]
tests/test_indirect.py::test_parametrized_indirect[application1]
tests/test_parametrized.py::test_parametrized[Desktop]
tests/test_parametrized.py::test_parametrized[Mobile]
  /usr/local/lib/python3.9/dist-packages/selene/core/configuration.py:939: DeprecationWarning: Was deprecated because "browser" term is not relevant to mobile context. Use `config.hold_driver_at_exit = ...` instead
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/test_fixtures.py::test_desktop - selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/113.0.5672.63/chromedriver unexpectedly exited. Status code was: 127
FAILED tests/test_fixtures.py::test_mobile - selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/113.0.5672.63/chromedriver unexpectedly exited. Status code was: 127
FAILED tests/test_indirect.py::test_parametrized_indirect[application0] - selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/113.0.5672.63/chromedriver unexpectedly exited. Status code was: 127
FAILED tests/test_parametrized.py::test_parametrized[Desktop] - selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/113.0.5672.63/chromedriver unexpectedly exited. Status code was: 127
FAILED tests/test_parametrized.py::test_parametrized[Mobile] - selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/113.0.5672.63/chromedriver unexpectedly exited. Status code was: 127
ERROR tests/test_fixtures.py::test_desktop - selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/113.0.5672.63/chromedriver unexpectedly exited. Status code was: 127
ERROR tests/test_fixtures.py::test_mobile - selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/113.0.5672.63/chromedriver unexpectedly exited. Status code was: 127
ERROR tests/test_indirect.py::test_parametrized_indirect[application0] - selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/113.0.5672.63/chromedriver unexpectedly exited. Status code was: 127
ERROR tests/test_indirect.py::test_parametrized_indirect[application1] - selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/113.0.5672.63/chromedriver unexpectedly exited. Status code was: 127
ERROR tests/test_parametrized.py::test_parametrized[Desktop] - selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/113.0.5672.63/chromedriver unexpectedly exited. Status code was: 127
ERROR tests/test_parametrized.py::test_parametrized[Mobile] - selenium.common.exceptions.WebDriverException: Message: Service /root/.wdm/drivers/chromedriver/linux64/113.0.5672.63/chromedriver unexpectedly exited. Status code was: 127
============== 5 failed, 1 skipped, 6 warnings, 6 errors in 7.88s ==============
[8mha:////4C4Vp2QlpsZzfTeOdR98BUzSp/Cshw309Y3jhtxPVJsMAAAAox+LCAAAAAAAAP9tjTESwiAURH/iWNhaeggyGUvHypah8QSYIEKY/wkQSeWJvJp3EM2MlVvs7NvmPV+wjgGOFDSzCgeDsTPMu0mXxTKF4eooM0sX1hFGcooJlQX16rSgoKRgSVXDisNGYecoGtQJttzKu2ycRN2cUyjfgUNt+hEeUPFiTjKkL8wBdrepj4Q/z18BzN4nqNv9p9o3geV5574AAAA=[0m[Pipeline] }
[8mha:////4EDCwwwkciLRZgBCJTW+14J6LuNdyMffZu8uD/fJg4sXAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOICEh2iSmu54QUmNsaJdWdsh6TiRXyNPxCIRMUWq51t5vmCZYpw5GixNdQ5So3D4Hs7LRw4dhfPA7Z8xoYpsTcozSBZm3pGydnAnKKEhYCVocZzcmQzrEWr7qryimx1ynH6DgJKp2/wgEJM5qxi/sIYYXPtdWL6ef4KYAwhQ7nbf2r7Bq/le42+AAAA[0m[Pipeline] // stage
[8mha:////4NSEppTd/cXuh7I3msZy1qocIYq7xT174Nziu2I/md2SAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRElSIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLsXZLsP9aSlGr0AAAA=[0m[Pipeline] }
[8mha:////4D4TmO8N5zCuVpXUmIiziOjbt9b2fCe5D2vJV2wZG5JCAAAApB+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRQqJBVLRWGl5gEmOcWHfBvpBUvIiv8QciIlGx1c4083pjmSKOHJ1qLLWeUuVVF3o3PTVwbK+BB9XwRVVMiYNVpR1Kru1pxpLFYl6WY6GxslQFTp6cYK0b8zBFMOSKs8TJHTRyX9/xRKanspgoXxgjNre+Tky/zt8Axq4T5Nu9INt9AIZLYcO9AAAA[0m[Pipeline] // node
[8mha:////4LxqiKFJkHf6xb+ex5IA+eJEUWrLgiwJdkZu28+Ha93FAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRNBSIitZKwwtMYowT6y7YF5KKF/E1/kBEJCq22plmXm8sU8SRo1ONpdZTqrzqQu+mpwaO7TXwoBq+qIopcbCqtEPJtT3NWLJYzMtyLDRWlqrAyZMTrHVjHqYIhlxxlji5g0bu6zueyPRUFhPlC2PE5tbXienX+RvA2HWCfLsXZLsPoFIGib0AAAA=[0m[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
